import React from 'react';
import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import '@/styles/globals.css';
import StyledComponentsRegistry from '../../themes/hocs/registry/StyledComponentsRegistry';
import StyledJsxRegistry from '../../themes/hocs/registry/StyledJsxRegistry';
import {QueryProvider} from '@/services/query';
import StoreProvider from '@/services/store/StoreProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StyledComponentsRegistry>
          <StyledJsxRegistry>
            <QueryProvider>
              <StoreProvider>{children}</StoreProvider>
            </QueryProvider>
          </StyledJsxRegistry>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
